CREATE TABLE liga(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL UNIQUE ,
    organizador VARCHAR(50) NOT NULL ,
    estado VARCHAR(15)  NOT NULL DEFAULT 'INSCRIPCION',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE equipo(
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(40) NOT NULL,
 liga_id BIGINT NOT NULL,
 FOREIGN KEY (liga_id) REFERENCES liga(id),
    UNIQUE (liga_id,nombre)
);